#include "DPOS_AutoRender.h"
#include "DPOS_DisplayManager.h"

RenderBlock_t DPOS_AUTORENDER_LIST[DPOS_AUTORENDER_QUEUES_AMOUNT];

bool DPOS_RenderCallbackPrio01() {
  return DPOS.getActivatedElements() & DPOS_ELEMENT_BIT_ANI_TRANS;
}
bool DPOS_RenderCallbackPrio02() {
  return DPOS.getActivatedElements() & DPOS_ELEMENT_BIT_MENU;
}
bool DPOS_RenderCallbackPrio03() {
  return DPOS.getActivatedElements() & DPOS_ELEMENT_BIT_ANI_FRAME;
}
bool DPOS_RenderCallbackPrio04() {
  return DPOS.getActivatedElements() & DPOS_ELEMENT_BIT_TEXTBODY;
}
bool DPOS_RenderCallbackPrio05() {
  return DPOS.getActivatedElements() & DPOS_ELEMENT_BIT_PROGRESS_INDICATOR;
}

#define DPOS_AUTORENDER_LIST_PRIO_01_SIZE 1
const uint32_t DPOS_AUTORENDER_LIST_MEMBER_PRIO_01[]{
  DPOS_ELEMENT_BIT_ANI_TRANS
};

#define DPOS_AUTORENDER_LIST_PRIO_02_SIZE 3
const uint32_t DPOS_AUTORENDER_LIST_MEMBER_PRIO_02[]{
  DPOS_ELEMENT_BIT_MENU,
  DPOS_ELEMENT_BIT_TAP_INDICATOR,
  DPOS_ELEMENT_BIT_STATUSBAR
};

#define DPOS_AUTORENDER_LIST_PRIO_03_SIZE 3
const uint32_t DPOS_AUTORENDER_LIST_MEMBER_PRIO_03[]{
  DPOS_ELEMENT_BIT_TEXTBODY,
  DPOS_ELEMENT_BIT_TAP_INDICATOR,
  DPOS_ELEMENT_BIT_ANI_FRAME
};

#define DPOS_AUTORENDER_LIST_PRIO_04_SIZE 1
const uint32_t DPOS_AUTORENDER_LIST_MEMBER_PRIO_04[]{
  DPOS_ELEMENT_BIT_TEXTBODY
};

#define DPOS_AUTORENDER_LIST_PRIO_05_SIZE 1
const uint32_t DPOS_AUTORENDER_LIST_MEMBER_PRIO_05[]{
  DPOS_ELEMENT_BIT_PROGRESS_INDICATOR
};




// typedef struct {
//   const uint32_t* elements;
//   uint32_t size;
//   RenderCallback callback;
// } RenderBlock_t;

void DPOS_setupAutoRender() {
  DPOS_AUTORENDER_LIST[0] = { DPOS_AUTORENDER_LIST_MEMBER_PRIO_01, DPOS_AUTORENDER_LIST_PRIO_01_SIZE, DPOS_RenderCallbackPrio01 };
  DPOS_AUTORENDER_LIST[1] = { DPOS_AUTORENDER_LIST_MEMBER_PRIO_02, DPOS_AUTORENDER_LIST_PRIO_02_SIZE, DPOS_RenderCallbackPrio02 };
  DPOS_AUTORENDER_LIST[2] = { DPOS_AUTORENDER_LIST_MEMBER_PRIO_03, DPOS_AUTORENDER_LIST_PRIO_03_SIZE, DPOS_RenderCallbackPrio03 };
  DPOS_AUTORENDER_LIST[3] = { DPOS_AUTORENDER_LIST_MEMBER_PRIO_04, DPOS_AUTORENDER_LIST_PRIO_04_SIZE, DPOS_RenderCallbackPrio04 };
  DPOS_AUTORENDER_LIST[4] = { DPOS_AUTORENDER_LIST_MEMBER_PRIO_05, DPOS_AUTORENDER_LIST_PRIO_05_SIZE, DPOS_RenderCallbackPrio05 };
}