#ifndef _DPOS_CFG_H
#define _DPOS_CFG_H
//contains all configurations for DPOS, some may be overwritten by other file!

#define DPOS_SCREEN_WIDTH 128
#define DPOS_SCREEN_HEIGHT 64

#define DPOS_SSD_1306_I2C_ADDRESS 0x3C

#define LOCK_PRG_ON_DISPLAY_FAIL true

#define DPOS_SCROLL_DELAY_DEFAULT 20  //initial delay (default 20)
#define DPOS_SCROLL_DELAY_START 15    //default 15
#define DPOS_SCROLL_DELAY_REVERSE 15  //default 15
#define DPOS_SCROLL_DELAY_TITLE_START 40



#define DPOS_VALUE_MARKER "{{value}}"
#define DPOS_TEXT_MARKER "{{text}}"


/*   STATUS BAR SETTINGS   */
#define DPOS_STATUS_BAR_POS_X 0
#define DPOS_STATUS_BAR_POS_Y 0
#define DPOS_STATUS_BAR_WIDTH DPOS_SCREEN_WIDTH
#define DPOS_STATUS_BAR_HEIGHT 16

/*   SCROLL INDICATOR SETTINGS   */
#define DPOS_SCROLL_INDICATOR_WIDTH 5
#define DPOS_SCROLL_INDICATOR_POS_Y (DPOS_STATUS_BAR_HEIGHT + 2)
#define DPOS_SCROLL_INDICATOR_POS_X (DPOS_SCREEN_WIDTH - DPOS_SCROLL_INDICATOR_WIDTH)
#define DPOS_SCROLL_INDICATOR_HEIGHT (DPOS_SCREEN_HEIGHT - DPOS_SCROLL_INDICATOR_POS_Y)

/*   TAP INDICATOR SETTINGS   */
#define DPOS_TAP_INDICATOR_POS_X 0
#define DPOS_TAP_INDICATOR_POS_Y 0
#define DPOS_TAP_INDICATOR_WIDTH 16
#define DPOS_TAP_INDICATOR_HEIGHT 16
#define DPOS_TAP_INDICATOR_TEXT_SIZE 1
#define DPOS_TAP_INDICATOR_RADIUS 7
#define DPOS_TAP_INDICATOR_MAX_INDICATOR_VALUE -1  //set to -1 for %10 display
#define DPOS_TAP_INDICATOR_HIDE_ON_0 true


/*   MENU SETTINGS   */
#define DPOS_MENU_TITLE_POS_X 16
#define DPOS_MENU_TITLE_POS_Y 0
#define DPOS_MENU_TITLE_WIDTH DPOS_SCREEN_WIDTH - DPOS_MENU_TITLE_POS_X - DPOS_SCROLL_INDICATOR_WIDTH
#define DPOS_MENU_TITLE_HEIGHT 18
#define DPOS_MENU_TITLE_OFFSET_IF_OVERSIZE 4
#define DPOS_MENU_ENTRIES_START_POS_Y DPOS_MENU_TITLE_HEIGHT + 2
#define DPOS_MENU_ENTRY_WIDTH DPOS_SCREEN_WIDTH - (DPOS_SCROLL_INDICATOR_WIDTH + 3)
#define DPOS_MENU_ENTRY_HEIGHT 10
#define DPOS_MENU_ENTRY_MAX_NUM 4










/*   DPOS ELEMENT BITS   */
#define DPOS_ELEMENT_BIT_TEXTBODY (1 << 0)
#define DPOS_ELEMENT_BIT_MENU (1 << 1)
#define DPOS_ELEMENT_BIT_ANI_TRANS (1 << 2)
#define DPOS_ELEMENT_BIT_ANI_FRAME (1 << 3)
#define DPOS_ELEMENT_BIT_TAP_INDICATOR (1 << 4)
#define DPOS_ELEMENT_BIT_STATUSBAR (1 << 5)
#define DPOS_ELEMENT_BIT_PROGRESS_INDICATOR (1 << 6)
#define DPOS_ELEMENT_BIT_SCROLL_INDICATOR (1 << 7)
#define DPOS_ELEMENT_BIT_CREATIVE_CANVAS (1 << 8)
// #define DPOS_ELEMENT_BIT_
// #define DPOS_ELEMENT_BIT_

#define TEXT_SIZE_SMALL 1
#define TEXT_SIZE_MEDIUM 2
#define TEXT_SIZE_LARGE 3

#define CHAR_HEIGHT_SMALL 8
#define CHAR_HEIGHT_MEDIUM 16
#define CHAR_HEIGHT_LARGE 24
#define CHAR_HEIGHT_EXTRALARGE 32

#define CHAR_WIDTH_SMALL 6
#define CHAR_WIDTH_MEDIUM 12
#define CHAR_WIDTH_LARGE 18
#define CHAR_WIDTH_EXTRALARGE 24
#define CHAR_WIDTH(x) ((x)*CHAR_WIDTH_SMALL)

#define DPOS_TASK_TIME_MS 25

#endif